export type MilitaryBranch =
  | "army"
  | "airForce"
  | "navy"
  | "marines"
  | "coastGuard"
  | "spaceForce";

export type MilitaryRanks = {
  [key in MilitaryBranch]: string[];
};

export const MILITARY_RANKS: MilitaryRanks = {
  army: [
    "Private",
    "Private First Class",
    "Specialist",
    "Corporal",
    "Sergeant",
    "Staff Sergeant",
    "Sergeant First Class",
    "Master Sergeant",
    "First Sergeant",
    "Sergeant Major",
    "Command Sergeant Major",
    "Sergeant Major of the Army",
    "Warrant Officer",
    "Chief Warrant Officer 2",
    "Chief Warrant Officer 3",
    "Chief Warrant Officer 4",
    "Chief Warrant Officer 5",
    "Second Lieutenant",
    "First Lieutenant",
    "Captain",
    "Major",
    "Lieutenant Colonel",
    "Colonel",
    "Brigadier General",
    "Major General",
    "Lieutenant General",
    "General",
    "General of the Army",
  ],
  airForce: [
    "Airman Basic",
    "Airman",
    "Airman First Class",
    "Senior Airman",
    "Staff Sergeant",
    "Technical Sergeant",
    "Master Sergeant",
    "Senior Master Sergeant",
    "Chief Master Sergeant",
    "Command Chief Master Sergeant",
    "Chief Master Sergeant of the Air Force",
    "Second Lieutenant",
    "First Lieutenant",
    "Captain",
    "Major",
    "Lieutenant Colonel",
    "Colonel",
    "Brigadier General",
    "Major General",
    "Lieutenant General",
    "General",
    "General of the Air Force",
  ],
  navy: [
    "Seaman Recruit",
    "Seaman Apprentice",
    "Seaman",
    "Petty Officer Third Class",
    "Petty Officer Second Class",
    "Petty Officer First Class",
    "Chief Petty Officer",
    "Senior Chief Petty Officer",
    "Master Chief Petty Officer",
    "Command Master Chief Petty Officer",
    "Master Chief Petty Officer of the Navy",
    "Warrant Officer",
    "Chief Warrant Officer 2",
    "Chief Warrant Officer 3",
    "Chief Warrant Officer 4",
    "Chief Warrant Officer 5",
    "Ensign",
    "Lieutenant Junior Grade",
    "Lieutenant",
    "Lieutenant Commander",
    "Commander",
    "Captain",
    "Rear Admiral (Lower Half)",
    "Rear Admiral",
    "Vice Admiral",
    "Admiral",
    "Fleet Admiral",
  ],
  marines: [
    "Private",
    "Private First Class",
    "Lance Corporal",
    "Corporal",
    "Sergeant",
    "Staff Sergeant",
    "Gunnery Sergeant",
    "Master Sergeant",
    "First Sergeant",
    "Master Gunnery Sergeant",
    "Sergeant Major",
    "Sergeant Major of the Marine Corps",
    "Warrant Officer",
    "Chief Warrant Officer 2",
    "Chief Warrant Officer 3",
    "Chief Warrant Officer 4",
    "Chief Warrant Officer 5",
    "Second Lieutenant",
    "First Lieutenant",
    "Captain",
    "Major",
    "Lieutenant Colonel",
    "Colonel",
    "Brigadier General",
    "Major General",
    "Lieutenant General",
    "General",
    "General of the Marine Corps",
  ],
  coastGuard: [
    "Seaman Recruit",
    "Seaman Apprentice",
    "Seaman",
    "Petty Officer Third Class",
    "Petty Officer Second Class",
    "Petty Officer First Class",
    "Chief Petty Officer",
    "Senior Chief Petty Officer",
    "Master Chief Petty Officer",
    "Command Master Chief Petty Officer",
    "Master Chief Petty Officer of the Coast Guard",
    "Warrant Officer",
    "Chief Warrant Officer 2",
    "Chief Warrant Officer 3",
    "Chief Warrant Officer 4",
    "Chief Warrant Officer 5",
    "Ensign",
    "Lieutenant Junior Grade",
    "Lieutenant",
    "Lieutenant Commander",
    "Commander",
    "Captain",
    "Rear Admiral (Lower Half)",
    "Rear Admiral",
    "Vice Admiral",
    "Admiral",
    "Fleet Admiral",
  ],
  spaceForce: [
    "Specialist 1",
    "Specialist 2",
    "Specialist 3",
    "Specialist 4",
    "Sergeant",
    "Technical Sergeant",
    "Master Sergeant",
    "Senior Master Sergeant",
    "Chief Master Sergeant",
    "Command Chief Master Sergeant",
    "Chief Master Sergeant of the Space Force",
    "Second Lieutenant",
    "First Lieutenant",
    "Captain",
    "Major",
    "Lieutenant Colonel",
    "Colonel",
    "Brigadier General",
    "Major General",
    "Lieutenant General",
    "General",
  ],
};

export const PROFILE_SECTIONS = {
  about: "About",
  whyVolunteer: "Why I Volunteer",
  volunteerism: "Previous NP Experience",
  jobs: "Current Occupation",
  education: "Education",
  military: "Military History",
  licenses: "Licenses",
  skills: "Skills",
  values: "Values",
};

export const EDIT_SECTIONS = {
  about: "about",
  background: "background",
  military: "militaryHistory",
  qualifications: "qualifications",
  availability: "availability",
  causes: "causes",
  friends: "friends",
  organizations: "organizations",
  activity: "activity",
  profile: "profile",
  donors: "donors",
  staff: "staff",
  values: "values",
  programs: "programs",
  documents: "documents",
  editRoster: "editRoster",
  createRoster: "createRoster",
  entityProfile: "entityProfile",
  entityAbout: "entityAbout",
};
